#!/bin/bash

SPOOL=/var/spool/usbip/bind

if [[ $1 == "-q" ]]
then
    exec &>/dev/null
fi

touch $SPOOL

while [[ -e $SPOOL ]]
do
  usbipd -D
  /usr/sbin/usbip bind -b 1-1.3
  sleep 10
done

/usr/sbin/usbip unbind -b 1-1.3

exit 0
